### ISSUE TITLE
Я хочу в твою команду (TRB-Exe)

### ISSUE THREAD

**Issue by VE-CR** [TRB-Exe/trb-exe.github.io#2]
### Привет!

**Как меня зовут?**
Меня не зовут. Я сам прихожу)))
Меня зовут Вадим!

**Сколько мне лет?**
В начале марта 2022-го года будет 14.

**Какие (не) языки программирования знаю?**
- HTML
- CSS
- Java
- JavaScript
- Python
- Bash
- Batch
- VB
- XML
- PHP

**Над чем сейчас** _раб_**отаю?**
Над:
- Библиотекой HTML
- Языком программирования "JELE" (ЖЕЛЕ)
- Своим сайтом

**Буду ли я помогать в разроботке [сайта](https://trbexe.ml)?**
Да

**Comment by TRB-Exe** [comment]
🤔

**Comment by VE-CR** [comment]
> thinking

Так что?
