### ISSUE TITLE
Как ты сделал панель навигации на своем сайте?

### ISSUE THREAD

**Issue by VE-CR** [TRB-Exe/trb-exe.github.io#4]
### `Как?`
`<a href="URL"><img src="IMAGE"></a>`
Так 👆️ что ли?
Или 👇🏾️ так?
`float: left;`

**Comment by TRB-Exe** [comment]
Нет.

**Comment by TRB-Exe** [comment]
При помощи div

**Comment by TRB-Exe** [comment]
Ну ещё при помощи <a> тега и использованы иконки material design
