### ISSUE TITLE
Помоги с доменом

### ISSUE THREAD

**Issue by VE-CR** [TRB-Exe/trb-exe.github.io#6]
### КАК???
Ничерта не понял!!!
Я не знаю, как узнать ip адресс [сайта](ve-cr.github.io)!
За то я разобрался, как создать DNS запись в FreeNom!

**Comment by TRB-Exe** [comment]
http://docs.github.com

**Comment by TRB-Exe** [comment]
https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site

**Comment by VE-CR** [comment]
### Я правельно сделал?
[Скриншот](https://imgur.com/ZoNoN9D.png)

**Comment by TRB-Exe** [comment]
Не так. Название никакое там не нужно просто A записи

**Comment by TRB-Exe** [comment]
А cname там username.github.io

**Comment by VE-CR** [comment]
Короче я тебя и всех понял [так](https://imgur.com/So1HoOq.png).

**Comment by TRB-Exe** [comment]
Не так

**Comment by TRB-Exe** [comment]
```
(Пустое поле в name) A Record GithubIP
(пустое поле в name) cname record username.github.io
```

**Comment by VE-CR** [comment]
[Так](https://i.imgur.com/653vzVe.png)?

**Comment by VE-CR** [comment]
Нет... Получилось [VECR.ML](https://vecr.ml)

**Comment by VE-CR** [comment]
Вот так.
Как то.

**Comment by VE-CR** [comment]
Привет!
Я тут сделал обнову [сайту](http://vecr.ml).
Посмотри пжпжпжпжпж!
